### ISSUE TITLE
recursive loop detected in template string: {{mysql_root_password}}

### ISSUE THREAD

**Issue by vesper8** [larastudio/stedding#1]
this line causes an infinite loop while running the playbook

```
mysql_root_password: "{{mysql_root_password}}"
```

because inside the "all" file, the variable name is also mysql_root_password

I got around it by renaming the variable to custom_mysql_root_password

**Comment by jasperf** [comment]
Thanks for the feedback @vesper8 . Good catch. Would you mind doing a pull request for this?

**Comment by jasperf** [comment]
@vesper8 did not get any feedback so closing this thread.
