### ISSUE TITLE
how to modify in order to pull the latest version of the galaxy roles

### ISSUE THREAD

**Issue by vesper8** [larastudio/stedding#3]
right now I see that all the roles were downloaded and committed to this repository, but I would like to use the latest versions to benefit from bug fixes and so on

sorry I'm very new to Ansible so I don't know how to do this on my own yet.. but I've tried many Laravel playbooks and so far yours is the most current that works on the latest Ubuntu and frankly it's the only one that's worked so far for me so kudos to you for sharing it!

**Comment by jasperf** [comment]
Well most roles can just be updated / replaced. That is what I have been doing until recently. Only when there are customized parts you will need to merge changes like in a git merge. Thanks for letting me know you like the efforts made and either good luck with Stedding or do join Anstead.
